### ISSUE TITLE
To listen well, get curious

### ISSUE THREAD

**Issue by e7h4n** [daily-reading/daily-reading#189]
https://www.benkuhn.net/listen/

**Comment by e7h4n** [comment]
一篇关于「倾听」的的 soft skill blog。
前置技能是[非暴力沟通](https://book.douban.com/subject/3533221/)，一种简单的沟通技巧。

**Comment by highestop** [comment]
> 一篇关于「倾听」的的 soft skill blog。
> 前置技能是[非暴力沟通](https://book.douban.com/subject/3533221/)，一种简单的沟通技巧。

强烈推荐这本书👍🏻
