### ISSUE TITLE
Cache is the Root of All Evil

### ISSUE THREAD

**Issue by eddieran** [daily-reading/daily-reading#25]
https://medium.com/box-tech-blog/cache-is-the-root-of-all-evil-e64ebd7cbd3b

**Comment by e7h4n** [comment]
这篇写的挺好的
感觉 box 的技术博客配图都不错

**Comment by highestop** [comment]
这篇为什么 close 了？

**Comment by e7h4n** [comment]
被选了

**Comment by highestop** [comment]
那如果有一篇文章，在 12.1 被提为 Issue，一个人 12.2 读了（ 此时笔记应为 12.1 ？），后来 12.3 被选了（ 要挪到 12.3 ？ ）😂

**Comment by e7h4n** [comment]
笔记跟着文章走，12.2 读的笔记自己找个地儿放吧

**Comment by highestop** [comment]
嗯，那可以先放到 Issue 下，或者自己先开个分支存了
