### ISSUE TITLE
OCTO 2.0：美团基于Service Mesh的服务治理系统详解

### ISSUE THREAD

**Issue by LiZhenNet** [daily-reading/daily-reading#348]
https://mp.weixin.qq.com/s/JmtDtfgrzTgO37F9Qn_NYQ

**Comment by LiZhenNet** [comment]
推荐一个中文的😝

**Comment by e7h4n** [comment]
感谢推荐，文章写的挺好，不过 daily-reading 是聚焦在英文文章的，除了获取知识以外，也希望通过这个项目来提升参与同学的英文阅读理解能力
