### ISSUE TITLE
Taking Ideas Seriously is Hard

### ISSUE THREAD

**Issue by e7h4n** [daily-reading/daily-reading#46]
https://neilkakkar.com/taking-ideas-seriously.html

讨论了「familiarity」与「taking sth seriously」的区别，举了一个熟悉的复利的例子。

比较有感触的是「复利」对于「学习」的影响。

短文，建议一读。

**Comment by highestop** [comment]
done

- 文中举了个 compounding 的例子
    - 大多数人提到 compounding 没有 take it a step further，比如 experiences and knowledge 的「 累进效应 」
    - Purposes are fragile though, and it’s easy to get lost in the tool, instead of the overall goal.
    - The greatest returns first.
- 扣题一下，taking ideas seriously 是对 familiarity 的反思，即「 以为知道 」就没「 深入思考 」
    - 作者建议尝试反问 What are the implications of (idea) in (field of interest)，将一个熟悉的概念带入一个具体的领域看能映射到什么东西
